# SETUP
baseurl = "/"
DefaultContentLanguage = "en"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] # disable hugo's content that we don't need...

title = "Markdown Clipper" # page title -> see ./layouts/partials/head.html

googleAnalytics = "" # if needed...

[author]
    name = "Yiren Lu"
    email = "yiren@tryfrindle.com"